### PR TITLE
Warnings

### PR DESCRIPTION
**Pull request by m-pilia**
I added `-Wextra` (that contains some useful warnings) and `-pedantic` (which warns for violations of ISO standard C++), and I made a few cleanups in the code accordingly.

### CODE REVIEW

**Comment by simeks** [comment]
I was about to change to `/W4` for MSVC but I realized we already run `/W4`. There's `/Wall` as well but I'm a bit hesitant since I get a wall of warnigns so large that it spans outside the history of cmd... Seems to be mostly the same thing though so I'll make an attempt to fix it.

**Comment by simeks** [comment]
Ok, yeah, so this is a nightmare, we should probably stick to `/W4` for now.

**Comment by m-pilia** [comment]
OK ahah
Then I'll merge as it is, if it is ok.

**Comment by simeks** [comment]
Sure, go ahead!

**Pull request merged**
